; ---------------------------------------------------------------------------
; fancy-feedback-form plugin configuration
; ---------------------------------------------------------------------------

plugin.fancy-feedback-form.enabled=true
