; ---------------------------------------------------------------------------
; fancy-info-card plugin configuration
; ---------------------------------------------------------------------------

plugin.fancy-info-card.enabled=true
